version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' 
    depends_on:
      - mongo
    environment:
      MONGO_URL: 'mongodb://host.docker.internal:27017/magic-transporters'

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' 
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:
    driver: local
